from __future__ import annotations

from sqlalchemy import (
    Column,
    ForeignKey,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)


def define_loop3_tables(metadata: MetaData) -> dict[str, Table]:
    stage_attempts = Table(
        "stage_attempts",
        metadata,
        Column("stage_attempt_id", String(32), primary_key=True),
        Column("owner_kind", String(30), nullable=False),
        Column("owner_id", String(100), nullable=False),
        Column("consumer_job_id", String(32), ForeignKey("jobs.job_id")),
        Column("work_item_id", String(32), ForeignKey("work_items.work_item_id")),
        Column("stage", String(100), nullable=False),
        Column("status", String(30), nullable=False),
        Column("resource_name", String(100)),
        Column("attempt_number", Integer, nullable=False),
        Column("started_sequence", Integer, nullable=False),
        Column("finished_sequence", Integer),
        Column("diagnostic_code", String(100)),
        Column("generation_id", String(32)),
        Column("runtime_kind", String(10)),
        Column("profile_id", String(100)),
        Column("runtime_fingerprint", String(64)),
        Column("pipeline_fingerprint", String(64)),
        Column("input_fingerprint", String(64)),
        Column("output_fingerprint", String(64)),
        Column("discarded", Integer, nullable=False, default=0),
        Column("error_kind", String(50)),
    )
    checkpoints = Table(
        "checkpoints",
        metadata,
        Column("checkpoint_id", String(32), primary_key=True),
        Column("owner_kind", String(30), nullable=False),
        Column("owner_id", String(100), nullable=False),
        Column("job_id", String(32), ForeignKey("jobs.job_id")),
        Column("work_item_id", String(32), ForeignKey("work_items.work_item_id")),
        Column("stage", String(100), nullable=False),
        Column("sequence", Integer, nullable=False),
        Column("payload_json", Text, nullable=False),
    )
    resource_slots = Table(
        "resource_slots",
        metadata,
        Column("resource_name", String(100), primary_key=True),
        Column("capacity", Integer, nullable=False),
        Column("last_granted_job_id", String(32), ForeignKey("jobs.job_id")),
        Column("grant_sequence", Integer, nullable=False),
    )
    leases = Table(
        "leases",
        metadata,
        Column("lease_id", String(32), primary_key=True),
        Column(
            "resource_name",
            String(100),
            ForeignKey("resource_slots.resource_name"),
            nullable=False,
        ),
        Column("holder_kind", String(20), nullable=False),
        Column("holder_id", String(100), nullable=False),
        Column("job_id", String(32), ForeignKey("jobs.job_id")),
        Column("work_item_id", String(32), ForeignKey("work_items.work_item_id")),
        Column(
            "stage_attempt_id",
            String(32),
            ForeignKey("stage_attempts.stage_attempt_id"),
        ),
        Column("slot_index", Integer, nullable=False, default=0),
        Column("instance_id", String(64)),
        Column("worker_id", String(100)),
        Column("acquired_sequence", Integer, nullable=False),
        Column("released_sequence", Integer),
        Column("acquired_at", String(40)),
        Column("heartbeat_at", String(40)),
        Column("expires_at", String(40)),
        Column("released_at", String(40)),
        Column("generation", Integer, nullable=False, default=1),
        Column("fencing_token", String(100)),
        Column("release_reason", String(100)),
        Column("status", String(20), nullable=False),
    )
    conflict_keys = Table(
        "conflict_keys",
        metadata,
        Column("conflict_key", String(200), primary_key=True),
        Column(
            "job_id",
            String(32),
            ForeignKey("jobs.job_id", ondelete="CASCADE"),
            nullable=False,
        ),
        Column("active", Integer, nullable=False),
        UniqueConstraint("job_id", name="uq_conflict_key_job"),
    )
    dependencies = Table(
        "dependencies",
        metadata,
        Column("dependency_id", String(32), primary_key=True),
        Column(
            "job_id",
            String(32),
            ForeignKey("jobs.job_id", ondelete="CASCADE"),
            nullable=False,
        ),
        Column("depends_on_job_id", String(32), ForeignKey("jobs.job_id")),
        Column("frozen_result_ref", String(200)),
        Column("status", String(30), nullable=False),
    )
    shared_evidence_work = Table(
        "shared_evidence_work",
        metadata,
        Column("shared_work_id", String(32), primary_key=True),
        Column("fingerprint", String(200), nullable=False, unique=True),
        Column("image_sha256", String(64), nullable=False),
        Column("pipeline_fingerprint", String(100), nullable=False),
        Column("image_relative_path", String(500)),
        Column("execution_mode", String(10), nullable=False, default="fake"),
        Column("runtime_kind", String(10)),
        Column("profile_id", String(100)),
        Column("runtime_fingerprint", String(64)),
        Column("status", String(30), nullable=False),
        Column("artifact_ref", String(200)),
        Column("output_json", Text),
        Column("output_fingerprint", String(64)),
        Column("reference_count", Integer, nullable=False),
        Column("runnable_consumer_count", Integer, nullable=False),
        Column("diagnostic_code", String(100)),
        Column("record_version", Integer, nullable=False, default=1),
        Column("retry_generation", Integer, nullable=False, default=0),
        Column("retry_budget", Integer, nullable=False, default=1),
        Column("attempt_count", Integer, nullable=False, default=0),
        Column("failure_propagation_id", String(64)),
    )
    shared_evidence_consumers = Table(
        "shared_evidence_consumers",
        metadata,
        Column(
            "shared_work_id",
            String(32),
            ForeignKey("shared_evidence_work.shared_work_id", ondelete="CASCADE"),
            nullable=False,
        ),
        Column(
            "work_item_id",
            String(32),
            ForeignKey("work_items.work_item_id", ondelete="CASCADE"),
            nullable=False,
        ),
        Column("image_role", String(20), nullable=False),
        Column("status", String(30), nullable=False),
        UniqueConstraint(
            "shared_work_id",
            "work_item_id",
            "image_role",
            name="uq_shared_evidence_consumer",
        ),
    )
    control_idempotency = Table(
        "control_idempotency",
        metadata,
        Column("operation", String(100), nullable=False),
        Column("idempotency_key", String(200), nullable=False),
        Column("request_hash", String(64), nullable=False),
        Column(
            "job_id",
            String(32),
            ForeignKey("jobs.job_id", ondelete="CASCADE"),
            nullable=False,
        ),
        Column("result_record_version", Integer, nullable=False),
        Column("result_status", String(30), nullable=False),
        UniqueConstraint(
            "operation",
            "idempotency_key",
            name="uq_control_idempotency_operation_key",
        ),
    )
    shared_work_retry_requests = Table(
        "shared_work_retry_requests",
        metadata,
        Column(
            "shared_work_id",
            String(32),
            ForeignKey("shared_evidence_work.shared_work_id", ondelete="CASCADE"),
            nullable=False,
        ),
        Column("idempotency_key", String(200), nullable=False),
        Column("expected_record_version", Integer, nullable=False),
        Column(
            "stage_attempt_id",
            String(32),
            ForeignKey("stage_attempts.stage_attempt_id"),
            nullable=False,
        ),
        Column("created_at", String(40), nullable=False),
        UniqueConstraint(
            "shared_work_id",
            "idempotency_key",
            name="uq_shared_work_retry_request",
        ),
    )
    scheduler_meta = Table(
        "scheduler_meta",
        metadata,
        Column("key", String(100), primary_key=True),
        Column("value", String(200), nullable=False),
    )
    ocr_run_generations = Table(
        "ocr_run_generations",
        metadata,
        Column("generation_id", String(32), primary_key=True),
        Column(
            "work_item_id",
            String(32),
            ForeignKey("work_items.work_item_id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        Column("pipeline_fingerprint", String(64), nullable=False),
        Column("primary_runtime_kind", String(10), nullable=False),
        Column("next_runtime_kind", String(10), nullable=False),
        Column("status", String(30), nullable=False),
        Column("committed_runtime_kind", String(10)),
        Column("committed_profile_id", String(100)),
        Column("committed_runtime_fingerprint", String(64)),
        Column("loading_output_json", Text),
        Column("unloading_output_json", Text),
        Column("loading_output_fingerprint", String(64)),
        Column("unloading_output_fingerprint", String(64)),
        Column("diagnostic_code", String(100)),
        Column("record_version", Integer, nullable=False, default=1),
        Column("created_at", String(40), nullable=False),
        Column("updated_at", String(40), nullable=False),
    )
    return {
        "stage_attempts": stage_attempts,
        "checkpoints": checkpoints,
        "resource_slots": resource_slots,
        "leases": leases,
        "conflict_keys": conflict_keys,
        "dependencies": dependencies,
        "shared_evidence_work": shared_evidence_work,
        "shared_evidence_consumers": shared_evidence_consumers,
        "control_idempotency": control_idempotency,
        "shared_work_retry_requests": shared_work_retry_requests,
        "scheduler_meta": scheduler_meta,
        "ocr_run_generations": ocr_run_generations,
    }
